version: 0.2
phases:
  install: # install python 3.9 on the build container, so SAM can do its thing
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install --upgrade aws-sam-cli # update the SAM cli so SAM deploy will work
  pre_build:
    commands:
      - echo "Running unit tests"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building SAM deployment"          
      - sam build
      - echo "Pushing the SAM deployment"
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cloud-resume-challenge
  post_build:
    commands:
      - echo "Uploading website contents"
      - aws s3 sync --delete ./resume-site s3://www.kylerloucks.click
      - echo "Build completed on `date`"